# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-20 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=250, verbose_name='slug')),
                ('collection', models.BooleanField(default=False, verbose_name='collection')),
                ('category', models.BooleanField(default=False, verbose_name='category')),
            ],
            options={
                'get_latest_by': 'date_added',
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Inv_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='photos', verbose_name='image')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='view count')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=250, verbose_name='slug')),
                ('caption', models.TextField(blank=True, verbose_name='caption')),
                ('date_added', models.DateTimeField(auto_now=True, verbose_name='date added')),
            ],
            options={
                'get_latest_by': 'date_added',
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='gallery', to='hello.Photo', verbose_name='photos'),
        ),
    ]
